### PR TITLE
Support HTTPS protocol in node.js client

### PR DESCRIPTION
**Pull request by jaquadro**
A small change to support the HTTPS protocol in the node client.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @jaquadro , nice improvement! 

Is the protocol indeed `'https:'`? with a colon? that's odd. Well, anyway...

**Comment by josdejong** [comment]
This should be available in `v0.4.0` now, would be great if you can check whether everything works correctly.

**Comment by jaquadro** [comment]
Everything looks good!

**Comment by josdejong** [comment]
:+1:

**Pull request merged**
