### PR TITLE
Added typescript types to allow better integration

### PR DESCRIPTION
**Pull request by rgolea**
* Added typings to the package.
* Update package.json

This should solve #25

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @rgolea , this looks good to me. Are there things that need to be addressed before merging this PR? (You've marked it as a Draft)

**Comment by rgolea** [comment]
@josdejong yeah, for some reason, and I didn't have the time to look better into it (sorry for that), it loses the `server` typings. I will have it this week though. Also, do you plan on changing the project to compile to typescript? Would love to take a shot at it and also help remove some not needed polyfills.

**Comment by josdejong** [comment]
Though I still maintain the library, I have no plans to put effort in `timesync` right now. 

If you or someone else create a PR refactoring the library into TS I will be happy to review and merge it though, help would be very welcome.

**Comment by rgolea** [comment]
I'm starting to refactor everything so I'm closing this PR at the moment. Please, @josdejong let me know if you agree to put it inside a monorepository. I want to use [NX](http://nx.dev) for that.

I want to fix the typescript issues but also use less polyfills (#30) and allow less instalation for the different packages. Are you okay with having something like: `@timesync/server`, `@timesync/consumer` and `@timesync/peer` (if needed)?

**Comment by josdejong** [comment]
@rgolea I hadn't heard of NX before, but I'm ok with that if you think it's a good idea :). I'm curious to see how that will work out.

**Comment by rgolea** [comment]
@josdejong it's basically Lerna on steroids. The problem I had was that I couldn't expose some internal typings.

I decided to go with this to have several packages and this way, we also prevent installing unnecessary parts.

I will finish this and I will show you the repo. If you like it, we can proceed with it, if not, we can scratch it off entirely.

**Comment by josdejong** [comment]
👍  thanks!

**Comment by crossan007** [comment]
I took a different approach and refactored the whole source to TypeScript and configured `tsc` to emit type declarations  https://github.com/crossan007/timesync

**Pull request closed without merging**
