### PR TITLE
Move source to src, build ES5 version to lib using babel directly

### PR DESCRIPTION
**Pull request by electrified**
Hi! Many thanks for the library.

As per comments on one of the earlier pull requests, using the library in Webpack projects causes warnings due to the bundling, so it would be nice to have an ES5 but not bundled version in the module

This commit moves the source to src and produces an ES5 version in lib using Babel. The contents of dist is unaffected.

### CODE REVIEW

**Comment by josdejong** [comment]
Great! Thanks of doing the refactoring.

**Comment by josdejong** [comment]
I've released v0.3.0. Would be great if you could give this a try and see whether I didn't break anything.

**Comment by electrified** [comment]
Have given it a test, all seems to be working OK.

Many thanks for merging.

**Comment by josdejong** [comment]
ok great!

**Pull request merged**
