### PR TITLE
Fix for timeout occurring before xhr success

### PR DESCRIPTION
**Pull request by DerekKeeler**
Fixes the remaining part of #11. I may have changed the intent of the way the code was handling send errors so let me know if I'm missing something.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @DerekKeeler, the send method failing and not handling that error looks like a plausible cause! Thanks for taking the time to put a PR together.

A few questions about your PR:
- Shouldn't the timeout stay there in the `rpc` method?
- The API currently uses Promises, so to keep that consistent it may make sense to return a Promise from the `send` method instead of a callback. What do you think?
- Do you know of a way to replicate the rapid-fire issue consistently? So far I've never been able to replicate the issue myself.

**Comment by DerekKeeler** [comment]
Thanks for taking a look @josdejong. To answer your questions:

- Shouldn't the timeout stay there in the rpc method?
Unless there is some other reason I'm missing (and if there is please let me know) relying on the request timeout should be sufficient. The error I'm seeing is being caused because the rpc timeout is completing even though the request eventually returned successfully. This is because there is a slight desynchronization between when the rpc timeout occurs and when the request timeout occurs. In this case the the actual HTTP request is our source of truth as it is the only piece that truly determines that a request took too long and cancels the request.

- The API currently uses Promises, so to keep that consistent it may make sense to return a Promise from the send method instead of a callback. What do you think?
Totally happy to make that switch and I think it's a really good idea. The only blocking issue to this is that the request fetch would need to be refactored to return a promise rather than use a callback. I'm happy to take on this task, I just didn't want to be so presumptuous about a codebase I'm not the maintainer of. Unless I hear otherwise I'll update my PR. 

- Do you know of a way to replicate the rapid-fire issue consistently? So far I've never been able to replicate the issue myself.
It's a pretty hard to replicate issue in the wild unless you just happen to have a server that responds in the window between the rpc timeout and the request timeout. You could artificially add a delay to the server being called but I found it easiest just to temporarily add time to the timeout value being sent to the XHR request.

**Comment by DerekKeeler** [comment]
@josdejong I've refectored request to use Promises and attempted to match the existing style. The previous callback approach was returning 3 values instead of just error and data so I took my best guess at acceptable return values for the promise resolve and reject.

**Comment by josdejong** [comment]
@DerekKeeler sorry for the late reply. 

Thanks for refactoring to use Promises! I see that you're now passing the configured timeout to the `post` function, that was indeed what I meant with not just removing the timeout function. I think we're almost there.

I think there is a left-over callback in the signature `send: function (to, data, callback) { ... }`, can you clean that up?

One last thought: right now we move the responsibility of handling timeouts from timesync to the implementation of the function `send`. I think is a good step, it clearly separates responsibilities. By default, `send` is implemented for HTTP, which indeed handles timeouts. But this may not be the case for other (custom) implementations like for websockets or webrtc (see the [advanced examples section](https://github.com/enmasseio/timesync/tree/master/examples/advanced)). To make this complete, maybe we should:
- pass the `timeout` as third parameter of `send`, to make it more obvious that you have to handle timeouts when overriding the build in implementation of `send`, and to make the custom implementations independent from internal configuration of timesync.
- force the function `send` to return a Promise, to make it obvious that the `send` function must handle success/failure. All existing code out there doesn't return anything from send, and will need to be changed. We can either throw an Error, or create print a console warning when a send doesn't return anything.

what do you think?

**Comment by josdejong** [comment]
Thanks for the updates @DerekKeeler , I really like the new API ! 

I think the socket.io example with the deferred Promise can be simplified a bit, will do that right away. I will also update the docs.

**Comment by josdejong** [comment]
@DerekKeeler I've just released `v1.0.0` containing your fix (think the library has been battle tested after all this time). Thanks again!

**Pull request merged**
