### PR TITLE
fix syntax error

### PR DESCRIPTION
**Pull request by cracker0dks**
fixes SyntaxError: Unexpected token { on line 129

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @cracker0dks. 

Looks like this notation `try { ... } catch { ... }` is not supported by Internet Explorer (works fine in other browsers).

**Comment by josdejong** [comment]
How did this error happen on your side @cracker0dks ? It's server side code. Are you using some older version of node.js?

**Comment by cracker0dks** [comment]
hey thanks for the merge. Node v8.16.0 also has that problem :)

**Comment by josdejong** [comment]
ahhh. You're aware that Node 8 has reached end of life?

Fixed now in `v1.0.7`

**Comment by cracker0dks** [comment]
yes, thanks. Was my mistake. Forgot to change back the version with nvm 👍 
thanks for the change anyway :D

**Pull request merged**
