### PR TITLE
Include lib directly and timestamp send function

### PR DESCRIPTION
**Pull request by SupremeTechnopriest**
Hello, 

I was having a few issues getting timsync up and running.  Firstly, browserify standalone wasn't working.  I couldn't include as a node_module (to then be browserified by my project).  I added browserify instructions to `package.json` which allows you to import directly from `lib`.

```javascript
import { create as timesync } from 'timesync/lib/timesync';
```

After I got the project to build I noticed that `sendTimestamp` was not responding.  Here I'm not sure if my implementation is acceptable because it will only work for express, but it does get me up and running.  I will maintain my own fork for now (I saw that you are busy) but if you want to visit the `sendTimestamp` function at some time let me know.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks for your PR @SupremeTechnopriest. Adding some config for browserify in the package.json is a good idea! 

I can't accept your PR right now since it only works in express like you aready say. How about extending the function like this:

```js
function sendTimestamp(req, res) {
  if (req.body) {
    // express.js or alike
    sendTimeStampResponse(res, req.body);
  }
  else {
    // node.js
    readRequestBody(req, function (body) {
      sendTimeStampResponse(res, body);
    });
  }
}

function readRequestBody (req) {
  // ... read the request body via req.on('data', ...)
}

function sendTimeStampResponse (res, id) {
  var data = {
    id: 'id' in body ? body.id : null,
    result: Date.now()
  };

  res.setHeader('Content-Type', 'application/json');
  res.status(200).send(JSON.stringify(data));
}

```

**Comment by SupremeTechnopriest** [comment]
Hey @josdejong,

I made the following changes.  I think its what we want.

```javascript 
function sendTimestamp(req, res) {
  if (req.body) {
    // express.js or similar
    sendTimeStampResponse(res, req.body);
  }
  else {
    // node.js
    readRequestBody(req, function (err, body) {
      sendTimeStampResponse(res, body);
    });
  }
}

function readRequestBody (req, callback) {
  var body = '';
  req.on('data', function (data) {
    body += data;

    // Too much POST data, kill the connection!
    if (body.length > 1e6) {
      req.connection.destroy();
    }
  });
  req.on('end', function () {
    callback(null, JSON.parse(body));
  });
}

function sendTimeStampResponse (res, id) {

  var data = {
    id: 'id' in body ? body.id : null,
    result: Date.now()
  };

  // Set content-type header
  res.setHeader('Content-Type', 'application/json');

  if(res.status && res.send) {
    // express.js or similar
    res.status(200).send(JSON.stringify(data));
  } else {
    // node.js
    res.writeHead(200);
    res.end(JSON.stringify(data));
  }

}

```

Needed to also check for the `res.status` and `res.send` methods in `sendTimestamp` as the responses are different for express vs node.

**Comment by SupremeTechnopriest** [comment]
Added in an error to the callback.  `readRequestBody` now looks like this:

```javascript
function readRequestBody (req, callback) {
  var body = '';
  req.on('data', function (data) {
    body += data;

    // Too much POST data, kill the connection!
    if (body.length > 1e6) {
      callback(new Error('Too much post data. Killing connection...'), null);
      req.connection.destroy();
    }
  });
  req.on('end', function () {
    callback(null, JSON.parse(body));
  });
}
```

**Comment by josdejong** [comment]
Thanks, I think we're getting there! 

Have you actually tried the code with both http and express? I get an error in the `sendTimeStampResponse` function, there is no variable `body` defined there.

**Comment by SupremeTechnopriest** [comment]
I haven't tested it in a pure `http` setup.  I see the issue though.  I'll push a fix.

**Comment by josdejong** [comment]
Thanks. Should be easy to test: `npm run build`, then open one of the http examples like [/examples/basic/http](https://github.com/enmasseio/timesync/tree/master/examples/basic/http)

**Comment by SupremeTechnopriest** [comment]
Okay that is tested.  Stupid mistake... Needed to rename argument from `id` to `body`:

```javascript
function sendTimeStampResponse (res, id) { ... }
```
to
```javascript
function sendTimeStampResponse (res, body) { ... }
```

**Comment by josdejong** [comment]
Thanks. I guess it was my mistake in the first place, looking at the code snippet I posted ;)

**Comment by josdejong** [comment]
I've released v0.2.2 containing your fixes. Thanks again!

**Comment by SupremeTechnopriest** [comment]
Awesome! It was my pleasure.  Thanks for your work on this lib. :)

**Comment by Aaronius** [comment]
First of all, thank you so much for building this lib! It's exactly what I was looking for.

Question related to this PR: are the files in the lib directory intentionally supposed to still have import statements? I'd like to require the lib files in using webpack but I don't want to configure my webpack for that stage of babel. In my experience lib files are typically transpiled to es5 so they're ready to go for the vast majority of consumers without requiring them to configure transpilation on their end.

Thanks again!

**Comment by josdejong** [comment]
@Aaronius the files under `/lib` are actually the source files (that has been the way of naming the node.js world though I use `/src` in more recent projects). The bundled ES5 files are available in the `/dist` folder.

**Comment by Aaronius** [comment]
Usually `src` is the es6 code (if any), `lib` is what's transpiled from `src` into es5 (but not bundled), and `dist` is the transpiled, bundled code typically used for hosting on a CDN and loading through a script tag. The `main` node in `package.json` usually refers to the entry file inside `lib`.

As it stands right now, if I `require('timesync')` using webpack, it pulls in `dist/timesync.min.js` which isn't desirable because it contains browserify overhead that is unnecessary and limits the amount of optimization that can happen. Webpack also warns about this: 

```
WARNING in ./~/timesync/dist/timesync.min.js
Critical dependencies:
1:438-445 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/timesync/dist/timesync.min.js 1:438-445
```

Unfortunately, I can't require in the `lib` code without also setting up babel in my project, which also isn't desirable.

I highly recommend putting the code in src, transpiling into lib, and bundling into dist, then changing the `main` node in `package.json` to point to the entry file in lib.

 Your call though. It's your project. Thank you again for building it. It seems to be working quite well.

**Comment by SupremeTechnopriest** [comment]
Honestly, I would just use [rollup](https://github.com/rollup/rollup) and export in formats `es` and `iife` for client side components, and `es` and `cjs` for the server side components.  Then you can use the [module](https://github.com/rollup/rollup/wiki/pkg.module) in package.json for the `es` build and `main` for the `cjs` build.  Then we can also get tree shaking for free.

**Comment by josdejong** [comment]
@Aaronius wow, you're right. Never realized that. We should put that right with a refactoring and a (breaking) release.

@SupremeTechnopriest I'm open for switching to another bundler. I like rollup (I have tried to use it before but without success, various sorts of limitations and issues). At least we should make sure the library works nicely with all major bundlers (webpack, browserify, rollup).

**Comment by electrified** [comment]
Many thanks for the library! This is just a +1 for @Aaronius's comments: including an ES5 but not bundled version would be great as I'm getting the same warnings when attempting to use in a webpack project.

Thanks again! :)

**Pull request merged**
